### PR TITLE
Add Type information to header

### PR DESCRIPTION
**Pull request by laroccajoseph**
Joseph La Rocca did this.

### CODE REVIEW

**Comment by X-sam** [comment]
Sure looks like I did it.

**Comment by laroccajoseph** [comment]
I went to do it now and there was nothing for me to do. The code had already been edited and I cannot change the code in class. If there is anything you want me to do please message me

**Comment by X-sam** [comment]
Fork this repository, steptools/NC.js
Do not fork Sam-son/NC.js

**Comment by laroccajoseph** [comment]
Thank you, I was not aware. Have not used git before

**Comment by laroccajoseph** [comment]
I have it done, ready to submit the pull request. But it will no longer let me when I get to the page, any help?

**Pull request closed without merging**
