### PR TITLE
hw5

### PR DESCRIPTION
**Pull request by GrahamAtkinson035**

### CODE REVIEW

**Comment by X-sam** [comment]
You should be making changes to the `ProbeDemo` branch not master.  
Also, you did not incorporate the fixes from Tuesday's class, so your code is wrong.   
Also also, you commited your personal changes to `config.js`

**Comment by GrahamAtkinson035** [comment]
I branched from ProbeDemo, I assumed that all changes I made from there
would be to my branch. I made all the changes the lecture notes covered
(this includes the changes to config.js, which is why I commited them), if
I was supposed to make other changes they were not explained in the
instructions for the homework.

**Comment by GrahamAtkinson035** [comment]
It seems that I correctly made and committed changes to the ProbeDemo
branch first, but at some point I accidentally switched branches and made
the same changes to the master branch as well.

**Comment by X-sam** [comment]
You should submit a Pull Request based on the right branch, then

**Pull request closed without merging**
